import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import ThemeProvider from "@/components/ui/themeProvider";
import Navbar from "@/components/Navigation/Navigation";

const inter = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Voyager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <StoreProvider>
            <Navbar />
            {children}
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
